### ISSUE TITLE
原图返回是空啊

### ISSUE THREAD

**Issue by winterLiao** [RITL/RITLImagePickerDemo#12]

**Comment by RITL** [comment]
原图是在
```
- (void)photosViewController:(UIViewController *)viewController images:(NSArray<UIImage *> *)images infos:(NSArray<NSDictionary *> *)infos
{
    //获得原比例的图片
    NSLog(@"%@", NSStringFromSelector(_cmd));

}
```
这里面获得的吗?

**Comment by RITL** [comment]
@winterLiao

**Comment by winterLiao** [comment]
- (void)photosViewController:(UIViewController *)viewController
                       datas:(NSArray <NSData *> *)datas
{
    NSLog(@"%@", NSStringFromSelector(_cmd));

}
这个datas返回是空的。

**Comment by winterLiao** [comment]
还有建议点击取消应该也写个代理

**Comment by RITL** [comment]
好的，下个版本我加一下那个取消的代理 @winterLiao

**Comment by RITL** [comment]
您好，刚刚更新了一个2.2.4版本，修复了一下那个datas回调方法永远返回空的问题，并新增了dismiss回调，您看一下，如果可以了告诉我一下，谢谢啦 @winterLiao

**Comment by winterLiao** [comment]
我用的模拟器没问题了 跑真机不行？

**Comment by RITL** [comment]
真是是可以的，我再看看，感觉会不会是icloud图片的事 @winterLiao

**Comment by RITL** [comment]
真机 @winterLiao

**Comment by winterLiao** [comment]
不知道什么情况，可能我这边问题吧..dissmiss那个代理也不走..模拟器上是可以的

**Comment by RITL** [comment]
啊，这么奇怪.. 能不能重新真机安装一下看看，我这里真机是可以的呢 @winterLiao

**Comment by winterLiao** [comment]
我直接把库拖到项目中就使用就可以了，之前用pod导入的不行(已经更新到2.2.4了，代码也是新的)，所以问题是啥我也不知道了...

**Comment by RITL** [comment]
好奇怪呀，我一直在手机上走也可以，😔 @winterLiao

**Comment by winterLiao** [comment]
你可以试下整个新的工程，然后用pod导入试试，如果没问题，估计是我这边操作的问题吧。

**Comment by RITL** [comment]
![image](https://user-images.githubusercontent.com/16571056/47991745-fe392e80-e125-11e8-92b7-5f17b05ba4c0.png)
新的工程我试了一下，可以，可能不知道是什么问题，我把这个issue标注一下。

**Comment by winterLiao** [comment]
ok 我用着了 感谢哈 有问题我再反馈
