### ISSUE TITLE
你好，我选好图片点击发送后，我原图和缩略图的代理方法都会走。上一个版本是根据我选择调用对应的回调；请问这是我那里使用错误了吗

### ISSUE THREAD

**Issue by 826888099** [RITL/RITLImagePickerDemo#16]

**Comment by RITL** [comment]
不好意思这么晚了才回复您，是这样的，原图和缩略图的回调是不管他选不选择原图的，基本上只要把这个代理方法实现了就会走的。您是需要知道具体的他选没选择原图吗；数据上传的话一般用的是那个data的回调代理

**Comment by RITL** [comment]
@826888099

**Comment by 826888099** [comment]
感谢你的回复 ，我最近在调试推送这块。 感觉关闭应用 杀死应用 的消息处理还不少 不知道保活那些在最新版本怎么应用&nbsp;





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bluears <notifications@github.com&gt;
发送时间: 2020年1月8日 10:35
收件人: RITL/RITLImagePickerDemo <RITLImagePickerDemo@noreply.github.com&gt;
抄送: 徐恒 <826888099@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[RITL/RITLImagePickerDemo] 你好，我选好图片点击发送后，我原图和缩略图的代理方法都会走。上一个版本是根据我选择调用对应的回调；请问这是我那里使用错误了吗 (#16)




不好意思这么晚了才回复您，是这样的，原图和缩略图的回调是不管他选不选择原图的，基本上只要把这个代理方法实现了就会走的。您是需要知道具体的他选没选择原图吗；数据上传的话一般用的是那个data的回调代理
