### ISSUE TITLE
master 分支,预览视频的时候 主线程 EXC_BREAKPOINT:

### ISSUE THREAD

**Issue by minsol** [RITL/RITLImagePickerDemo#17]
![Snip20200506_2](https://user-images.githubusercontent.com/18135746/81146736-739bee80-8fab-11ea-96d4-ad64bba2131a.png)

**Comment by RITL** [comment]
好的，十分感谢反馈，master分支已经修复了，但是Pod还没来得及更新，十分感谢 @minsol

**Comment by RITL** [comment]
pod已更新
