### ISSUE TITLE
你好，视频选项问题

### ISSUE THREAD

**Issue by DeadAndLife** [RITL/RITLImagePickerDemo#18]
我设置了不选择视频，虽然视频不可点了，但是依旧在列表中显示，能处理一下吗

**Comment by DeadAndLife** [comment]
RITLPhotosGroupTableViewController的cancle没有使用本地化，视频问题也是在这里发现的，分组下有单独的视频分组

**Comment by RITL** [comment]
好的，我马上看一下 @DeadAndLife  谢谢😀

**Comment by RITL** [comment]
```
pod repo update
pod update RITLPhotos
```
更新一下，看看2.3.4中 `configation` 的 `hiddenGroupAllVideo`能否满足咱的功能需求 @DeadAndLife
