### ISSUE TITLE
获取缩略图的时候图片模糊

### ISSUE THREAD

**Issue by DogAndCatIsHome** [RITL/RITLImagePickerDemo#2]
我使用了这个方法,但是图片的质量还是不理想,有些模糊, option.deliveryMode = PHImageRequestOptionsDeliveryModeFastFormat;//控制照片质量

**Comment by RITL** [comment]
您好，可以使用option.deliveryMode = PHImageRequestOptionsDeliveryModeOpportunistic，
搭配[PHImageManager defaultManager]requestImageForAsset:t targetSize:contentMode: options: resultHandler:方法截取图片
记得size的width和height要与[UIDevice currentDevice].scale相乘适配当前屏幕的显示 @DogAndCatIsHome

**Comment by DogAndCatIsHome** [comment]
谢谢，终于解决了。




发自网易邮箱大师
在2017年07月20日 18:17，RITL 写道：

您好，可以使用option.deliveryMode = PHImageRequestOptionsDeliveryModeOpportunistic，
搭配[PHImageManager defaultManager]requestImageForAsset:t targetSize:contentMode: options: resultHandler:方法截取图片
记得size的width和height要与[UIDevice currentDevice].scale相乘适配当前屏幕的显示

**Comment by DogAndCatIsHome** [comment]
你好：相册预览大图的时候是从模糊到清晰的一个效果，有办法直接变成清晰图吗？




发自网易邮箱大师
在2017年07月21日 11:53，RITL 写道：

Closed #2.
