### ISSUE TITLE
无法适配iPhone11 PRO 以上的livephoto，不能直接写asset.mediaSubtypes==PHAssetMediaSubtypePhotoLive来判断

### ISSUE THREAD

**Issue by shacokent** [RITL/RITLImagePickerDemo#21]
不能直接写asset.mediaSubtypes==PHAssetMediaSubtypePhotoLive
iPhone11 PRO 以上这个值变成了520，直接 == 会不识别
需改成
if(asset.mediaSubtypes&PHAssetMediaSubtypePhotoLive){
  //Code
}

**Comment by RITL** [comment]
👍，当时确实写的时候是我失误了，没注意到，谢谢你呀😀
