### ISSUE TITLE
相册图片没有全部加载

### ISSUE THREAD

**Issue by l770826421** [RITL/RITLImagePickerDemo#5]
导入RITLImagePicker的文件后，使用简单加载，只加载了部分图片。

**Comment by RITL** [comment]
很感谢关注到我的这个图片库，很抱歉带来这个问题，目前这个工具库我正在重构中，并对功能进行了拓展以及修复，暂时还没有发布..所以如果着急需要使用图片库，可以暂时考虑一下其他的图片库，很抱歉..😞😞 @l770826421

**Comment by RITL** [comment]
😀已经重构完毕了，谢谢你啦
