### ISSUE TITLE
bundle图片资源显示不出来

### ISSUE THREAD

**Issue by acerpeanut** [RITL/RITLImagePickerDemo#7]
RITLPhotos.bundle里面的所有图片资源都没显示出来。

例如下面这个界面：
![screen shot 2018-06-26 at 5 20 38](https://user-images.githubusercontent.com/5311733/41902302-b0e0c63e-7965-11e8-945d-8aade74392fb.png)

左上角的”返回“图标 和 右上角的”勾选“图标 都没显示出来。
@"RITLPhotos.bundle/ritl_bottomUnselected".ritl_image 
@"RITLPhotos.bundle/ritl_bottomSelected".ritl_image
都返回了 nil。
我用的是pod 1.3.1版本。

推荐使用类似下面这种方式来获取图片资源：

![default](https://user-images.githubusercontent.com/5311733/41902638-873ff326-7966-11e8-82ea-7dec32908989.png)

**Comment by RITL** [comment]
好的，我回去马上就修改一下，谢谢😀 @acerpeanut

**Comment by RITL** [comment]
更新了一下新版本，按照bundle的形式进行了图片加载，我没有iPod，所以也没办法测试，你更新一下2.1.4版本吧，如果还有问题，麻烦继续回复我一下，谢谢😀

**Comment by RITL** [comment]
😀您好，已经更新了一个版本，因为我没有iPod，所以没有办法进行测试，但已经按照MJ的思路使用了Bundle进行加载，谢谢 @acerpeanut

**Comment by acerpeanut** [comment]
谢谢，使用新版本后，图标显示出来了😁
</br>
</br>
另外我说的pod是指cocoapods 😂

**Comment by RITL** [comment]
😂哈哈哈哈，好尴尬呀
