### ISSUE TITLE
如果不利用用cocoapods，可以使用这个框架吗

### ISSUE THREAD

**Issue by Qu000** [RITL/RITLImagePickerDemo#9]
如果不利用用cocoapods，可以使用这个框架吗？
我cocoapods install的时候，出现了 cocopods Unable to find a specification for `RITLKit`

**Comment by RITL** [comment]
可以的，不过还是需要关联一下 `Masonry` 和  `RITLKit`，你看看是不是Pod版本有点低呀 @Qu000
